#! /bin/sh

prefix=/opt/local
exec_prefix=/opt/local
AFTERIMAGE_LIBS="-L/opt/local/lib -lAfterImage  -lAfterBase -lfreetype -lz -lbz2 -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lcairo -lgobject-2.0 -lglib-2.0 -lintl -ltiff -lX11 -lSM -lICE -lXext -ljpeg -lpng -lz -lm"
AFTERIMAGE_LIBS_EXTERNAL="-L/opt/local/lib -lfreetype -lz -lbz2 -L/opt/local/lib -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lcairo -lgobject-2.0 -lglib-2.0 -lintl   -ltiff -lX11  -L/opt/local/lib   -lSM -lICE -lXext -ljpeg -lpng -lz -lm"
HAVE_AFTERBASE="yes"
AFTERIMAGE_PREF_FORMAT="png"
AFTERIMAGE_X_SUPPORT="yes"


usage()
{
  cat <<EOF
Usage: afterimage-config [OPTIONS] [LIBRARIES]
Options:
 [--prefix[=DIR]]
 [--exec-prefix[=DIR]]
 [--version]
 [--libs [--external-only]] 
 [--libtool]
 [--cflags]
 [--have-afterbase]
 [--preferred-image-format]
 [--have-x-support]
EOF
  exit $1
}

if test $# -eq 0 ; then
  usage 1 1>&2
fi

while test $# -gt 0 ; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
  --prefix=*)
    prefix=$optarg
    local_prefix=yes
    ;;
  --prefix)
    echo_prefix=yes
    ;;
  --exec-prefix=*)
    exec_prefix=$optarg
    exec_prefix_set=yes
    local_prefix=yes
    ;;
  --exec-prefix)
    echo_exec_prefix=yes
    ;;
  --version)
    echo 1.20
    exit 0
    ;;
  --cflags)
    echo_cflags=yes
    ;;
  --libs)
    echo_libs=yes
    ;;
  --libtool)
    echo_libtool=yes
    ;;
  --have-afterbase)
    echo_have_afterbase=yes
    ;;
  --have-x-support)
    echo_have_x_support=yes
    ;;
  --preferred-image-format)
    echo_preferred_image_format=yes
    ;;
  --external-only)
    echo_external_only=yes
    ;;
  *)
    usage 1 1>&2
    ;;
  esac
  shift
done

if test "$local_prefix" = "yes" ; then
    if test "$exec_prefix_set" != "yes" ; then
      exec_prefix=$prefix
    fi
fi

if test "$echo_prefix" = "yes" ; then
 echo $prefix
fi

if test "$echo_exec_prefix" = "yes" ; then
 echo $exec_prefix
fi

if test "$echo_cflags" = "yes" ; then
 cflags="-I/opt/local/include/libAfterImage"
 if test "/opt/local/include" != "/usr/include" ; then
  echo $cflags -I/opt/local/include
 else
  echo $cflags
 fi
fi

if test "$echo_libs" = "yes" ; then
 libs="$AFTERIMAGE_LIBS_EXTERNAL"
 if test "$echo_external_only" != "yes"; then 
 	if test "yes" = "yes" ; then
        	libs="-lAfterBase $libs"
 	fi
 	libs="-lAfterImage $libs" 
	if test "/opt/local/lib" != "/usr/lib" ; then
  		echo -L/opt/local/lib $libs
 	else
  		echo $libs
 	fi
 else
        echo $libs
 fi
fi

if test "$echo_libtool" = "yes" ; then
 convlib="libAfterImage.la"
 echo /opt/local/lib/$convlib
fi

if test "$echo_have_afterbase" = "yes" ; then
 echo "yes"
fi

if test "$echo_have_x_support" = "yes" ; then
 echo "yes"
fi

if test "$echo_preferred_image_format" = "yes" ; then
 echo "png"
fi

# EOF
