#ifndef AFTERBASE_CONFIG_H_HEADER_INCLUDED
#define AFTERBASE_CONFIG_H_HEADER_INCLUDED

#define AFTERBASE_VERSION	1.14

#define		AFTERBASE_DEBUG_ALLOCS		1
#define		AFTERBASE_DEBUG_TRACE 		1
#define		AFTERBASE_DEBUG_TRACE_X		1 
#define		AFTERBASE_X_DISPLAY		1

#endif
